cubes:
  - name: products
    sql_table: "\"ECOM\".\"PRODUCTS\""

    joins: []

    dimensions:
# primary and foreign keys 
      - name: id
        sql: "{CUBE}.\"ID\""
        type: number
        primary_key: true

# time columns 
      - name: created_at
        sql: "{CUBE}.\"CREATED_AT\""
        type: time

# columns
      - name: product_category
        sql: "{CUBE}.\"PRODUCT_CATEGORY\""
        type: string

      - name: name
        sql: "{CUBE}.\"NAME\""
        type: string

# aggregations 
    measures:
      - name: number_of_products
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

