views:
  - name: order_information
    description: "This view contains information about orders placed"

# tables to be included in view    
    cubes:  
      - join_path: orders
        includes: "*"
        excludes:
          - id
          - user_id
          - completed_at
          - number_of_orders_year_to_date
          - number_of_orders_quarter_to_date
          - number_of_orders_month_to_date

      - join_path: orders.users 
        includes:
          - age
          - gender
          - city 
          - state
          - number_of_users
          - first_name
          - last_name
          - full_name 

      - join_path: orders.line_items
        includes:
          - total_revenue
          - number_of_items

      - join_path: orders.line_items.products 
        includes:
          - name
          - product_category
          - number_of_products

# data access policiies 
    access_policy:
      - role: admin

      - role: leadership

      - role: Developer

      - role: manager 
        member_level:
          includes:
            - last_name
          excludes:
            - first_name
            - full_name

      - role: 'default'
        member_level:
          excludes:
            - first_name 
            - last_name
            - full_name
        row_level:
          filters:
            - member: "order_information.state"
              operator: equals
              values: 
               - "{{add_rls(COMPILE_CONTEXT) | safe}}"

    meta:
# Excel drill-down hierarchies 
      hierarchies:
        - name: "Geography"
          levels:
            - state
            - city

#Excel measure folders 
      folders:
          - name: "Counts"
            members:
              - number_of_orders
              - number_of_completed_orders
              - number_of_items
          - name: "Totals"
            members:
              - total_revenue
          - name: "Averages"
            members:
              - average_days_to_complete
          - name: "Percentages"
            members:
              - completed_order_percentage